# fly.toml file generated for wwwallet on 2022-10-18T15:10:11+02:00

app = "wwwallet"
primary_region = "cdg"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  processes = ["app"]